# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none


pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/industryplatform/ci.mgmt.yml
    - sdk/industryplatform/Azure.ResourceManager.IndustryPlatform/


  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/industryplatform/ci.mgmt.yml
    - sdk/industryplatform/Azure.ResourceManager.IndustryPlatform/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: industryplatform
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.IndustryPlatform
      safeName: AzureResourceManagerIndustryPlatform
